### ISSUE TITLE
Test room

### ISSUE THREAD

**Issue by mblesel** [spacesisters/SpaceSisters#12]
A Test stage with the characters and interactive objects in the game.
Can be used as a Tutorial and during development for testing.

**Comment by mblesel** [comment]
I am trying to put everything we created so far together into one scene, so we can use that to start creating actual levels.

The problem is, that I am currently a bit confused which scenes contain the most current versions of 
stuff and some of the scenes just don't work when I open them on my PC (hundreds of errors).

I would be nice if all of you could list the things that are in a state that they could be used in a scene
and also a few words on how to set the gameobjects up correctly (which scripts to include, what values
for the SerializedFields, etc.)

Following is a list of GameObjects/Prefabs for which I would need to now which version i should
use for the TestRoom:

Characters:  (I guess the ArturMainCharacter1 Prefab?) 
Camera/Splitscreen scripts: 
Which Stage Prefabs? 
Collectables: (Are they in the SpaceSisters repo? I could not find anything)
Enemies: 
UI: (The current scenes with UI Elements don't work for me at all. I only get white areas and the .png
files in Materials/Victoria/Ressources/ are broken for me. Do they work for the rest of you?)

Did I forget something?

**Comment by ghost** [comment]
1. The most current scenes are in: Main/Scenes; I use "Ice" for most of my testing. But they don't include the collectables or enemies
2. Characters: Use the Prefabs in Resources/Prefabs/Main/PlayerCharacters. They have to be in the Resources folder because they are spawned during runtime. This means that they are loaded (and Resources.Load demans that they are in a folder called "Resources")
3. Camera/Splitscreen: The current implementation of Julius' Camera doesn't work so well, So I've temporarilly made one. It's in  Resources/Prefabs/Main/Misc
4. Stage Prefabs: We have a jump pad so far and platforms that move to certain locations. We'd need at least the gravity reverser. Other than the rest doesn't need to be prefabs. You just have to put them in the rooms and they become prefabs with the room. 
5 & 6: Collectables and Enemies are not in the repo yet.
7: UI works for me. Are you using the ones in Scenes/Main?

**Comment by mblesel** [comment]
I think we can close this, since we made a test room together in the last exercise.
