### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by ghost** [spacesisters/SpaceSisters#34]
![grafik](https://user-images.githubusercontent.com/44801751/61649285-7b570480-acb1-11e9-9314-db2b93bf5ffb.png)

On Menu Scene - happens when move the stick first and then you press "a" on an xbox controller. Doesn't crash the game. Game only starts, when you press "b" on New Game. Should maybe be "a" 

But if you press "a" immediately after starting the game, it works. But if you press "a" on anything other than "New Game" it gives that error and then you need to press "b" to continue.

Also I don't have xbox_p1_button_circle in the input settings.
Can you guys confirm/check this? 

~~Doesn't seem grave but would be nice to fix~~ Definately needs checking

This also happens in other menus

**Comment by mblesel** [comment]
should be fixed with 897911d88f9a8d5c0542590f5d2943094773d75f 

I need someone with an xbox controller to test it out.
In MenuUI there where some wrong assignments for the submit/cancel buttons.
 xbox_p1_button_circle does not exist. the xbox mappings are named after the keys on the 
xbox controllers (e.g xbox_p1_button_b instead of _circle for the ps4 controller).

I did changed the assignments to 'a' being submit and 'b' being cancel
